### ISSUE TITLE
Merge spectrum display components from SDRangelSpectrum app

### ISSUE THREAD

**Issue by f4exb** [f4exb/sdrangelcli#1]
This is to create a component capable to render the spectrum data that would be sent from a SDRangel instance when this ticket is implemented: https://github.com/f4exb/sdrangel/issues/224

**Comment by f4exb** [comment]
Example of Canvas uage: https://medium.com/@tarik.nzl/creating-a-canvas-component-with-free-hand-drawing-with-rxjs-and-angular-61279f577415

**Comment by drom** [comment]
I can help with creating such a component if you are still interested.

**Comment by f4exb** [comment]
Sure! This has been more or less stalled due to other priorities but still a desirable feature.

**Comment by drom** [comment]
Do you have Idea about desired API or data format that component woul accept?

**Comment by f4exb** [comment]
There were ideas listed above in my comments from last February but I didn't go further due to the lack of examples. I know OpenwebRX uses web sockets to transmit and render spectrum information. I am not against web sockets in this context if it facilitates implementation.

**Comment by f4exb** [comment]
If you look at the SDRangel counterpart https://github.com/f4exb/sdrangel/issues/224 I already had a look at possible implementation using WebRTC which could be nice but again was stuck because of lack of examples.

**Comment by f4exb** [comment]
The current implementation as an independent app works fine. It is perfectly and may be even more practical to have it in a separate tab in the browser.
