### ISSUE TITLE
Http failure response

### ISSUE THREAD

**Issue by Valstee** [f4exb/sdrangelcli#25]
Hi f4exb,
I try to remotly control sdrangel with sdrangelcli from an other PC but I think I'm doing something wrong :
1. Run SDRangel on PC1

2. Run http-server on PC1

![MicrosoftTeams-image (21)](https://user-images.githubusercontent.com/77800144/115424364-efb03600-a1fe-11eb-9b80-20a52016eeb9.png)

3. Open sdrangel client in a web browser on PC1 (it works !) :

![MicrosoftTeams-image (22)](https://user-images.githubusercontent.com/77800144/115424787-4ae22880-a1ff-11eb-9c7c-548307eb9616.png)

4. But it doesn't work with this URL (192.168.1.35:8091/sdrangel) on PC1 :

![MicrosoftTeams-image (23)](https://user-images.githubusercontent.com/77800144/115425219-b7f5be00-a1ff-11eb-942b-a1c2dcfdaa60.png)

5. and then doesn't work on PC 2 :
![sdrangel](https://user-images.githubusercontent.com/77800144/115425809-3b171400-a200-11eb-8f82-b4039394ac7b.PNG)

Do you know the error that I make ? (PC1 and PC2 are on the same network and the UDP streaming is working between both)
Thanks,
Valentin

**Comment by Valstee** [comment]
Find the answer in "sdrangel issue #508" !

**Comment by Klammraute** [comment]
how did u solve it, i dont find a issue #508?

**Comment by Valstee** [comment]
Sdrangel must also be listening on this IP. 
It depends on how you run the application but it should look something like this: 

`/opt/install/sdrangel/bin/sdrangel -a 192.168.1.35`
