### ISSUE TITLE
sdrplay frequency band already in khz

### ISSUE THREAD

**Issue by c0d3rx** [f4exb/sdrangelcli#39]
in
https://github.com/f4exb/sdrangelcli/blob/master/src/app/device-details/sdrplay/sdrplay.component.ts

frequency bands reported  by http://\<myserver\>/sdrangel/deviceset/0/device/report

are already in khz, so there is no need to divide again by 1000

https://github.com/f4exb/sdrangelcli/blob/47a2a88def6166ae4fd080934c165f70c1294be1/src/app/device-details/sdrplay/sdrplay.component.ts#L162

**Comment by f4exb** [comment]
Maybe this is an issue in SDRangel because I think usually the frequencies in the API are in Hz.

**Comment by f4exb** [comment]
Note that sample rates should also be given in bare units i.e. S/s but this is not divided by 1000 in the component. The fix in SDRangel will require it to be fixed on this side as well.

**Comment by f4exb** [comment]
Correction done in SDRangel
